"""Database access for ingestion — the write side.

Prisma (packages/db/schema.prisma) OWNS the schema and migrations. This module writes
to the Prisma-created tables via parameterized SQL, matching Prisma's (mixed-case,
quoted) table and column names.

Central invariant: `upsert_records()` REJECTS any record without a SourceRef, so
un-sourced facts can never enter the database. Every record also creates a SourceRef
row recording exactly what was fetched and when.

Two Prisma realities this layer handles explicitly:
  * `@default(cuid())` is generated by Prisma Client, NOT the database — so every
    INSERT must supply an `id`. We generate one per inserted row.
  * Foreign keys reference generated cuid PKs, so records resolve FKs by NATURAL key
    (Record.refs) via lookup SQL just before writing.
"""

from __future__ import annotations

import uuid
from collections.abc import Iterable, Mapping
from typing import Any
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

from sqlalchemy import create_engine, text
from sqlalchemy.engine import Connection

from .config import settings
from .sources.base import Record, SourceRef

# Prisma-only query params that libpq/psycopg don't understand.
_PRISMA_ONLY_PARAMS = {"schema", "pgbouncer", "connection_limit", "connect_timeout", "pool_timeout"}


def normalize_db_url(url: str) -> str:
    """Turn a Prisma-style DATABASE_URL into a SQLAlchemy+psycopg3 URL.

    - force the psycopg (v3) driver
    - drop Prisma-specific query params (e.g. ?schema=public) that psycopg rejects
    """
    if not url:
        return "postgresql+psycopg://localhost/mimir"
    parts = urlsplit(url)
    scheme = parts.scheme
    if scheme in ("postgres", "postgresql"):
        scheme = "postgresql+psycopg"
    kept = [(k, v) for k, v in parse_qsl(parts.query) if k not in _PRISMA_ONLY_PARAMS]
    return urlunsplit((scheme, parts.netloc, parts.path, urlencode(kept), parts.fragment))


# gssencmode=disable: libpq tries a GSSAPI-encryption probe before SSL by default;
# in sandboxed networks that probe packet can be dropped and the connection hangs
# (TCP itself succeeds). Disabling it makes psycopg connect immediately. Harmless
# where GSSAPI isn't used. (Same class of issue as the IPv4 forcing in http.py.)
engine = create_engine(
    normalize_db_url(settings.database_url),
    connect_args={"gssencmode": "disable"},
    future=True,
)


class MissingSourceError(ValueError):
    """Raised when a fact-bearing record arrives without provenance."""


class UnknownEntityError(ValueError):
    """Raised when a record targets an entity this layer doesn't know how to write."""


def gen_id() -> str:
    """A unique text id for a new row (the column is text; format is irrelevant)."""
    return "c" + uuid.uuid4().hex[:24]


# --- Per-entity write configuration ----------------------------------------
# table:          quoted Postgres table name
# conflict:       columns forming the ON CONFLICT target (a unique index in Prisma)
# enums:          column -> Postgres enum type name (needs an explicit ::"Type" cast)
# provenance:     provenance columns this table actually has
ENTITY_CONFIG: dict[str, dict[str, Any]] = {
    "State": {"table": '"State"', "conflict": ["fips"], "enums": {}, "provenance": [], "has_id": False},
    "District": {
        "table": '"District"',
        "conflict": ["geoid"],
        "enums": {},
        "provenance": ["sourceRefId", "fetchedAt"],
        "has_id": True,
    },
    "Seat": {
        "table": '"Seat"',
        "conflict": ["districtId", "cycle", "type"],
        "enums": {"type": "ElectionType"},
        "provenance": [],
        "has_id": True,
    },
    "Candidate": {
        "table": '"Candidate"',
        "conflict": ["fecCandidateId"],
        "enums": {"party": "Party"},
        "provenance": ["fetchedAt"],
        "has_id": True,
    },
    "Candidacy": {
        "table": '"Candidacy"',
        "conflict": ["candidateId", "seatId"],
        "enums": {"status": "IncumbencyStatus"},
        "provenance": [],
        "has_id": True,
    },
    "Demographics": {
        "table": '"Demographics"',
        "conflict": ["districtId"],  # @unique — one demographics row per district
        "enums": {},
        "provenance": ["fetchedAt"],
        "has_id": True,
    },
    "FinanceSummary": {
        "table": '"FinanceSummary"',
        "conflict": ["candidateId", "cycle"],
        "enums": {},
        "provenance": ["fetchedAt"],
        "has_id": True,
    },
    "Bill": {
        "table": '"Bill"',
        "conflict": ["congress", "billType", "billNumber"],
        "enums": {},
        "provenance": [],
        "has_id": True,
    },
    "BillSponsorship": {
        "table": '"BillSponsorship"',
        "conflict": ["billId", "candidateId"],
        "enums": {},
        "provenance": [],
        "has_id": True,
    },
}

# Resolve an entity's cuid id from a natural key (for FK resolution).
ID_LOOKUP: dict[str, str] = {
    "District": 'SELECT id FROM "District" WHERE geoid = :geoid',
    "Candidate": 'SELECT id FROM "Candidate" WHERE "fecCandidateId" = :fecCandidateId',
    "Seat": (
        'SELECT s.id FROM "Seat" s JOIN "District" d ON s."districtId" = d.id '
        'WHERE d.geoid = :geoid AND s.cycle = :cycle AND s.type = :type'
    ),
    "Bill": (
        'SELECT id FROM "Bill" WHERE congress = :congress '
        'AND "billType" = :billType AND "billNumber" = :billNumber'
    ),
}

# Source metadata by kind.
SOURCE_META: dict[str, dict[str, Any]] = {
    "FEC": {"homepage": "https://www.fec.gov", "reliability": 5},
    "CONGRESS": {"homepage": "https://www.congress.gov", "reliability": 5},
    "CENSUS": {"homepage": "https://www.census.gov", "reliability": 5},
    "X": {"homepage": "https://x.com", "reliability": 4},
    "CAMPAIGN_SITE": {"homepage": "", "reliability": 5},
    "HOUSE_CLERK": {"homepage": "https://disclosures-clerk.house.gov", "reliability": 5},
    "SENATE_LDA": {"homepage": "https://lda.senate.gov", "reliability": 5},
    "MIT_ELECTION_LAB": {"homepage": "https://electionlab.mit.edu", "reliability": 5},
}


def _col(name: str) -> str:
    return f'"{name}"'


def _placeholder(col: str, enums: Mapping[str, str]) -> str:
    """Bind placeholder, adding an enum cast where the column is a Postgres enum."""
    if col in enums:
        return f'CAST(:{col} AS "{enums[col]}")'
    return f":{col}"


def _ensure_source(conn: Connection, source: SourceRef) -> str:
    meta = SOURCE_META.get(source.kind.value, {"homepage": "", "reliability": 5})
    row = conn.execute(
        text(
            'INSERT INTO "Source" (id, kind, name, "homepageUrl", reliability) '
            'VALUES (:id, CAST(:kind AS "SourceKind"), :name, :homepage, :reliability) '
            'ON CONFLICT (kind, name) DO UPDATE SET "homepageUrl" = EXCLUDED."homepageUrl" '
            "RETURNING id"
        ),
        {
            "id": gen_id(),
            "kind": source.kind.value,
            "name": source.name,
            "homepage": meta["homepage"],
            "reliability": meta["reliability"],
        },
    ).one()
    return row[0]


def _insert_source_ref(conn: Connection, source: SourceRef, source_id: str) -> str:
    ref_id = gen_id()
    conn.execute(
        text(
            'INSERT INTO "SourceRef" (id, "sourceId", url, "fetchedAt") '
            "VALUES (:id, :source_id, :url, :fetched_at)"
        ),
        {"id": ref_id, "source_id": source_id, "url": source.url, "fetched_at": source.fetched_at},
    )
    return ref_id


def _resolve_refs(conn: Connection, rec: Record) -> dict[str, str]:
    resolved: dict[str, str] = {}
    for col, (entity, natural_key) in rec.refs.items():
        sql = ID_LOOKUP.get(entity)
        if sql is None:
            raise UnknownEntityError(f"No id lookup for referenced entity '{entity}'")
        row = conn.execute(text(sql), natural_key).first()
        if row is None:
            raise LookupError(f"{rec.entity}: could not resolve {col} -> {entity} {natural_key}")
        resolved[col] = row[0]
    return resolved


def _upsert_one(conn: Connection, rec: Record, sourceref_id: str) -> None:
    cfg = ENTITY_CONFIG.get(rec.entity)
    if cfg is None:
        raise UnknownEntityError(f"No write config for entity '{rec.entity}'")

    resolved = _resolve_refs(conn, rec)
    columns: dict[str, Any] = {**rec.key, **rec.data, **resolved}

    if "sourceRefId" in cfg["provenance"]:
        columns["sourceRefId"] = sourceref_id
    if "fetchedAt" in cfg["provenance"]:
        columns["fetchedAt"] = rec.source.fetched_at

    enums = cfg["enums"]
    conflict = cfg["conflict"]

    # Update-only: patch existing row's non-key columns; never insert (avoids NOT NULL
    # violations when we only have a few columns, e.g. attaching bioguideId).
    if rec.update_only:
        set_cols = [c for c in columns if c not in conflict]
        if not set_cols:
            return
        set_clause = ", ".join(f"{_col(c)} = {_placeholder(c, enums)}" for c in set_cols)
        where = " AND ".join(f"{_col(c)} = {_placeholder(c, enums)}" for c in conflict)
        conn.execute(
            text(f'UPDATE {cfg["table"]} SET {set_clause} WHERE {where}'), columns
        )
        return

    if cfg["has_id"]:
        columns["id"] = gen_id()

    col_names = list(columns.keys())
    insert_cols = ", ".join(_col(c) for c in col_names)
    insert_vals = ", ".join(_placeholder(c, enums) for c in col_names)

    # On conflict, refresh everything except id and the conflict-target columns.
    update_cols = [c for c in col_names if c != "id" and c not in conflict]
    if update_cols:
        set_clause = ", ".join(f'{_col(c)} = EXCLUDED.{_col(c)}' for c in update_cols)
        conflict_action = f"DO UPDATE SET {set_clause}"
    else:
        conflict_action = "DO NOTHING"

    sql = (
        f'INSERT INTO {cfg["table"]} ({insert_cols}) VALUES ({insert_vals}) '
        f'ON CONFLICT ({", ".join(_col(c) for c in conflict)}) {conflict_action}'
    )
    conn.execute(text(sql), columns)


def upsert_records(records: Iterable[Record], *, dry_run: bool = False) -> int:
    """Idempotently upsert records (in dependency order) with provenance.

    Every record MUST carry a SourceRef. In dry-run mode we validate presence and
    count without touching the database (FK resolution needs a live DB).
    """
    records = list(records)
    for rec in records:
        if rec.source is None:
            raise MissingSourceError(f"{rec.entity} {rec.key} has no SourceRef")

    if dry_run:
        return len(records)

    written = 0
    with engine.begin() as conn:
        source_ids: dict[tuple[str, str], str] = {}
        for rec in records:
            skey = (rec.source.kind.value, rec.source.name)
            if skey not in source_ids:
                source_ids[skey] = _ensure_source(conn, rec.source)
            sourceref_id = _insert_source_ref(conn, rec.source, source_ids[skey])
            _upsert_one(conn, rec, sourceref_id)
            written += 1
    return written


def seed_states(*, dry_run: bool = False) -> int:
    """Upsert the State reference table. Idempotent.

    Uses a single multi-row INSERT (one round-trip) rather than one statement per
    state — matters over a high-latency pooled connection.
    """
    from .reference.states import STATES

    if dry_run:
        return len(STATES)

    values = ", ".join(f"(:fips{i}, :abbr{i}, :name{i})" for i in range(len(STATES)))
    params: dict[str, Any] = {}
    for i, s in enumerate(STATES):
        params[f"fips{i}"], params[f"abbr{i}"], params[f"name{i}"] = s.fips, s.abbr, s.name

    with engine.begin() as conn:
        conn.execute(
            text(
                f'INSERT INTO "State" (fips, abbr, name) VALUES {values} '
                "ON CONFLICT (fips) DO UPDATE SET abbr = EXCLUDED.abbr, name = EXCLUDED.name"
            ),
            params,
        )
    return len(STATES)
